package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
)

const (
	apparmorMainProfile     = "/etc/apparmor.d/docker-helper-system"
	apparmorManagedFragment = "/etc/apparmor.d/docker-helper.d/managed-roots"
	apparmorLockPath        = "/run/lock/docker-helper-apparmor.lock"
)

const (
	fragmentHeader1 = "# Generated by docker-helper. Do not edit."
	fragmentHeader2 = "# Managed AppArmor workspace roots for docker-helper-system profile."
)

type apparmorManager struct {
	mainProfilePath      string
	managedFragmentPath  string
	lockPath             string
	runParser            func(args []string) error
	checkParserAvailable func() error
}

func newApparmorManager(
	mainProfile, managedFragment, lockPath string,
	runParser func(args []string) error,
	checkParserAvailable func() error,
) *apparmorManager {
	return &apparmorManager{
		mainProfilePath:      mainProfile,
		managedFragmentPath:  managedFragment,
		lockPath:             lockPath,
		runParser:            runParser,
		checkParserAvailable: checkParserAvailable,
	}
}

func newProductionParserRunner() func(args []string) error {
	return func(args []string) error {
		cmd := exec.Command("apparmor_parser", args...)
		var stderr bytes.Buffer
		cmd.Stderr = &stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("apparmor_parser %v: %w: %s", args, err, strings.TrimSpace(stderr.String()))
		}
		return nil
	}
}

func newProductionParserCheck() func() error {
	return func() error {
		if _, err := exec.LookPath("apparmor_parser"); err != nil {
			return errors.New("apparmor_parser not found in PATH")
		}
		return nil
	}
}

type inputError struct {
	msg string
}

func (e *inputError) Error() string { return e.msg }

func isInputError(err error) bool {
	_, ok := err.(*inputError)
	return ok
}

func validateRootPath(path string) (string, error) {
	if !filepath.IsAbs(path) {
		return "", &inputError{msg: "path must be absolute"}
	}

	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", &inputError{msg: fmt.Sprintf("path does not exist: %s", path)}
		}
		return "", &inputError{msg: fmt.Sprintf("cannot stat path: %v", err)}
	}
	if !info.IsDir() {
		return "", &inputError{msg: "path is not a directory"}
	}

	canonical, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", &inputError{msg: fmt.Sprintf("cannot resolve path: %v", err)}
	}

	if canonical == "/" {
		return "", &inputError{msg: "cannot use root directory as workspace root"}
	}

	for _, c := range canonical {
		switch c {
		case '*', '?', '[', ']', '{', '}', '\n', '\r':
			return "", &inputError{msg: fmt.Sprintf("path contains invalid character %q", string(c))}
		}
	}

	return canonical, nil
}

func escapeAppArmorPath(path string) string {
	return strings.ReplaceAll(path, `\`, `\\`)
}

func renderFragment(roots []string) []byte {
	sorted := make([]string, len(roots))
	copy(sorted, roots)
	sort.Strings(sorted)
	sorted = deduplicateStrings(sorted)

	var buf bytes.Buffer

	buf.WriteString(fragmentHeader1 + "\n")
	buf.WriteString(fragmentHeader2 + "\n")

	for _, root := range sorted {
		escaped := escapeAppArmorPath(root)
		buf.WriteString("\n")
		buf.WriteString("# root: " + root + "\n")
		buf.WriteString(escaped + "/ r,\n")
		buf.WriteString(escaped + "/** r,\n")
	}

	return buf.Bytes()
}

func parseFragment(data []byte) ([]string, error) {
	content := string(data)
	if !strings.HasSuffix(content, "\n") {
		return nil, errors.New("fragment missing trailing newline")
	}

	lines := strings.Split(content, "\n")

	if len(lines) < 2 {
		return nil, errors.New("fragment too short")
	}
	if lines[0] != fragmentHeader1 {
		return nil, errors.New("fragment header mismatch")
	}
	if lines[1] != fragmentHeader2 {
		return nil, errors.New("fragment header mismatch")
	}

	var roots []string
	for i := 2; i < len(lines); i++ {
		line := lines[i]
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "# root: ") {
			root := strings.TrimPrefix(line, "# root: ")
			roots = append(roots, root)
		}
	}

	sort.Strings(roots)
	deduped := deduplicateStrings(roots)

	expected := renderFragment(deduped)
	if !bytes.Equal(data, expected) {
		return nil, errors.New("fragment content does not match expected format (manually modified?)")
	}

	return deduped, nil
}

func deduplicateStrings(s []string) []string {
	if len(s) == 0 {
		return s
	}
	result := make([]string, 0, len(s))
	result = append(result, s[0])
	for i := 1; i < len(s); i++ {
		if s[i] != s[i-1] {
			result = append(result, s[i])
		}
	}
	return result
}

func (m *apparmorManager) acquireApparmorLock() (*os.File, error) {
	if err := os.MkdirAll(filepath.Dir(m.lockPath), 0755); err != nil {
		return nil, fmt.Errorf("cannot create lock directory: %w", err)
	}

	f, err := os.OpenFile(m.lockPath, os.O_CREATE|os.O_RDWR, 0600)
	if err != nil {
		return nil, fmt.Errorf("cannot open lock file: %w", err)
	}

	if err := syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		f.Close()
		if err == syscall.EWOULDBLOCK {
			return nil, errors.New("another apparmor operation is in progress")
		}
		return nil, fmt.Errorf("cannot acquire lock: %w", err)
	}

	return f, nil
}

func (m *apparmorManager) checkSymlink() error {
	info, err := os.Lstat(m.managedFragmentPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("cannot stat managed fragment: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return errors.New("managed fragment path is a symlink")
	}
	return nil
}

func (m *apparmorManager) readFragment() ([]string, error) {
	if err := m.checkSymlink(); err != nil {
		return nil, err
	}

	data, err := os.ReadFile(m.managedFragmentPath)
	if err != nil {
		if os.IsNotExist(err) {
			return []string{}, nil
		}
		return nil, fmt.Errorf("cannot read managed fragment: %w", err)
	}

	return parseFragment(data)
}

func (m *apparmorManager) writeFragment(roots []string) error {
	dir := filepath.Dir(m.managedFragmentPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("cannot create fragment directory: %w", err)
	}

	data := renderFragment(roots)

	tmp, err := os.CreateTemp(dir, "managed-roots-*.tmp")
	if err != nil {
		return fmt.Errorf("cannot create temp file: %w", err)
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot write temp file: %w", err)
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot set temp file mode: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot close temp file: %w", err)
	}
	if err := os.Rename(tmpName, m.managedFragmentPath); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot rename temp file: %w", err)
	}

	return nil
}

func (m *apparmorManager) reloadProfile() error {
	return m.runParser([]string{"-r", m.mainProfilePath})
}

func (m *apparmorManager) validateProfile() error {
	return m.runParser([]string{"--validate", m.mainProfilePath})
}

func (m *apparmorManager) getFragmentState() ([]byte, os.FileMode, error) {
	data, err := os.ReadFile(m.managedFragmentPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, 0644, nil
		}
		return nil, 0, err
	}
	info, err := os.Stat(m.managedFragmentPath)
	if err != nil {
		return data, 0644, nil
	}
	return data, info.Mode().Perm(), nil
}

func (m *apparmorManager) restoreFragmentFile(prevData []byte, prevMode os.FileMode) error {
	if prevData == nil {
		return os.Remove(m.managedFragmentPath)
	}

	dir := filepath.Dir(m.managedFragmentPath)
	tmp, err := os.CreateTemp(dir, "managed-roots-*.tmp")
	if err != nil {
		return fmt.Errorf("cannot create rollback temp file: %w", err)
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(prevData); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot write rollback temp file: %w", err)
	}
	if err := tmp.Chmod(prevMode); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot set rollback temp file mode: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot close rollback temp file: %w", err)
	}
	if err := os.Rename(tmpName, m.managedFragmentPath); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot rename rollback temp file: %w", err)
	}

	return nil
}

func (m *apparmorManager) rollbackFragment(prevData []byte, prevMode os.FileMode) error {
	if err := m.restoreFragmentFile(prevData, prevMode); err != nil {
		return err
	}
	if err := m.reloadProfile(); err != nil {
		return err
	}
	return nil
}

func (m *apparmorManager) listRoots() ([]string, error) {
	return m.readFragment()
}

func (m *apparmorManager) addRoot(path string) (string, error) {
	canonical, err := validateRootPath(path)
	if err != nil {
		return "", err
	}

	lockFile, err := m.acquireApparmorLock()
	if err != nil {
		return "", err
	}
	defer lockFile.Close()

	roots, err := m.readFragment()
	if err != nil {
		return "", err
	}

	for _, r := range roots {
		if r == canonical {
			return "already present", nil
		}
	}

	roots = append(roots, canonical)
	sort.Strings(roots)

	prevData, prevMode, _ := m.getFragmentState()

	if err := m.writeFragment(roots); err != nil {
		return "", err
	}

	if err := m.reloadProfile(); err != nil {
		rollbackErr := m.rollbackFragment(prevData, prevMode)
		if rollbackErr != nil {
			return "", fmt.Errorf("reload failed: %v; rollback also failed: %v", err, rollbackErr)
		}
		return "", fmt.Errorf("reload failed: %w", err)
	}

	return "added", nil
}

func (m *apparmorManager) removeRoot(path string) (string, error) {
	canonical, err := validateRootPath(path)
	if err != nil {
		return "", err
	}

	lockFile, err := m.acquireApparmorLock()
	if err != nil {
		return "", err
	}
	defer lockFile.Close()

	roots, err := m.readFragment()
	if err != nil {
		return "", err
	}

	newRoots := make([]string, 0, len(roots))
	found := false
	for _, r := range roots {
		if r == canonical {
			found = true
		} else {
			newRoots = append(newRoots, r)
		}
	}

	if !found {
		return "was not present", nil
	}

	prevData, prevMode, _ := m.getFragmentState()

	if err := m.writeFragment(newRoots); err != nil {
		return "", err
	}

	if err := m.reloadProfile(); err != nil {
		rollbackErr := m.rollbackFragment(prevData, prevMode)
		if rollbackErr != nil {
			return "", fmt.Errorf("reload failed: %v; rollback also failed: %v", err, rollbackErr)
		}
		return "", fmt.Errorf("reload failed: %w", err)
	}

	return "removed", nil
}

func (m *apparmorManager) check() error {
	if err := m.checkParserAvailable(); err != nil {
		return err
	}

	if _, err := os.Stat(m.mainProfilePath); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("main profile not found: %s", m.mainProfilePath)
		}
		return fmt.Errorf("cannot stat main profile: %w", err)
	}

	if _, err := m.readFragment(); err != nil {
		return fmt.Errorf("managed fragment is malformed: %w", err)
	}

	if err := m.validateProfile(); err != nil {
		return fmt.Errorf("profile validation failed: %w", err)
	}

	return nil
}
