package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"unicode"
	"unicode/utf8"
)

const (
	appArmorMainProfile           = "/etc/apparmor.d/docker-helper-system"
	appArmorManagedBoundariesPath = "/var/lib/docker-helper/apparmor/managed-boundaries"
	appArmorLockPath              = "/run/lock/docker-helper-apparmor.lock"
	appArmorParserPath            = "/usr/sbin/apparmor_parser"
)

const (
	fragmentHeader1       = "# Generated by docker-helper. Do not edit."
	fragmentHeader2       = "# Managed AppArmor workspace boundaries for docker-helper-system profile."
	legacyFragmentHeader2 = "# Managed AppArmor workspace roots for docker-helper-system profile."
)

type appArmorProfileManager struct {
	mainProfilePath     string
	managedFragmentPath string
	lockPath            string
	parserPath          string
	runParser           func(executable string, args []string) error
}

func newAppArmorProfileManager(
	mainProfile, managedFragment, lockPath, parserPath string,
	runParser func(executable string, args []string) error,
) *appArmorProfileManager {
	return &appArmorProfileManager{
		mainProfilePath:     mainProfile,
		managedFragmentPath: managedFragment,
		lockPath:            lockPath,
		parserPath:          parserPath,
		runParser:           runParser,
	}
}

func newProductionParserRunner() func(executable string, args []string) error {
	return func(executable string, args []string) error {
		cmd := exec.Command(executable, args...)
		var stderr bytes.Buffer
		cmd.Stderr = &stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("%s %v: %w: %s", filepath.Base(executable), args, err, strings.TrimSpace(stderr.String()))
		}
		return nil
	}
}

func newProductionAppArmorProfileManager() *appArmorProfileManager {
	return newAppArmorProfileManager(
		appArmorMainProfile,
		appArmorManagedBoundariesPath,
		appArmorLockPath,
		appArmorParserPath,
		newProductionParserRunner(),
	)
}

type inputError struct {
	msg string
}

func (e *inputError) Error() string { return e.msg }

// boundaryResult is the structured return value for addManagedBoundary and removeManagedBoundary.
type boundaryResult struct {
	Path    string
	Changed bool
}

// validateBoundaryLexical checks a path string without filesystem access.
// It is the authoritative lexical validator for stored managed boundaries.
func validateBoundaryLexical(path string) error {
	if !utf8.ValidString(path) {
		return &inputError{msg: "path is not valid UTF-8"}
	}
	if !filepath.IsAbs(path) {
		return &inputError{msg: "path must be absolute"}
	}
	if path == "/" {
		return &inputError{msg: "cannot use root directory as workspace root"}
	}
	if filepath.Clean(path) != path {
		return &inputError{msg: "path is not in clean form"}
	}
	if strings.HasSuffix(path, "/") {
		return &inputError{msg: "path must not end with /"}
	}
	for _, c := range path {
		switch c {
		case '*', '?', '[', ']', '{', '}':
			return &inputError{msg: fmt.Sprintf("path contains invalid character %q", string(c))}
		}
		if unicode.IsControl(c) {
			return &inputError{msg: fmt.Sprintf("path contains control character %q", string(c))}
		}
	}
	return nil
}

func validateBoundaryPathForAdd(path string) (string, appArmorBoundaryKind, error) {
	if !filepath.IsAbs(path) {
		return "", 0, &inputError{msg: "path must be absolute"}
	}

	// Use the issued-tree path policy for canonicalization and security
	// checks: a managed MAC boundary may be a directory or a regular file
	// (both are kinds an issued Session filesystem root may carry). The
	// kind is decided exactly once here — the caller syntax boundary — and
	// is persisted with the boundary.
	canonical, err := canonicalizeIssuedTreePathForAdd(path)
	if err != nil {
		return "", 0, &inputError{msg: err.Error()}
	}

	// AppArmor-specific lexical validation (format constraints for managed fragment).
	if err := validateBoundaryLexical(canonical); err != nil {
		return "", 0, err
	}

	info, err := os.Stat(canonical)
	if err != nil {
		return "", 0, &inputError{msg: fmt.Sprintf("cannot stat issued tree: %v", err)}
	}
	if info.IsDir() {
		return canonical, appArmorBoundaryDirectory, nil
	}
	if info.Mode().IsRegular() {
		return canonical, appArmorBoundaryRegularFile, nil
	}
	return "", 0, &inputError{msg: "issued tree is neither a directory nor a regular file"}
}

func validateBoundaryPathForRemove(path string) (string, error) {
	if !filepath.IsAbs(path) {
		return "", &inputError{msg: "path must be absolute"}
	}

	info, err := os.Stat(path)
	if err == nil {
		if info.IsDir() {
			canonical, err := filepath.EvalSymlinks(path)
			if err != nil {
				return "", &inputError{msg: fmt.Sprintf("cannot resolve path: %v", err)}
			}
			if err := validateBoundaryLexical(canonical); err != nil {
				return "", err
			}
			return canonical, nil
		}
		// Existing non-directory: treat as lexical stale boundary candidate.
		cleaned := filepath.Clean(path)
		if err := validateBoundaryLexical(cleaned); err != nil {
			return "", err
		}
		return cleaned, nil
	}

	if !os.IsNotExist(err) {
		return "", fmt.Errorf("cannot stat path: %w", err)
	}

	cleaned := filepath.Clean(path)
	if err := validateBoundaryLexical(cleaned); err != nil {
		return "", err
	}
	return cleaned, nil
}

func jsonQuote(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func escapeAppArmorPath(path string) string {
	path = strings.ReplaceAll(path, `\`, `\\`)
	path = strings.ReplaceAll(path, `"`, `\"`)
	return path
}

// appArmorBoundaryKind is the stable kind of one managed boundary, decided
// once when the boundary is added and persisted in the managed fragment.
// The kind decides which reachability rules the fragment renders; it is
// never re-derived from mutable current host state, so an unrelated
// fragment rewrite cannot reinterpret an issued regular-file boundary into
// directory semantics (or the reverse).
type appArmorBoundaryKind int

const (
	appArmorBoundaryDirectory appArmorBoundaryKind = iota
	appArmorBoundaryRegularFile
)

// appArmorManagedBoundary is one managed boundary with its stable kind.
type appArmorManagedBoundary struct {
	Path string
	Kind appArmorBoundaryKind
}

// appArmorBoundaryFileMarker is the JSON kind marker persisted in the
// managed fragment's root-json metadata for a regular-file boundary. A
// boundary whose root-json metadata is the plain quoted path (the pre
// file-root fragment form) is a directory boundary: the legacy fragment
// represented directory boundaries only.
const appArmorBoundaryFileMarker = "regular-file"

type appArmorBoundaryFileMeta struct {
	Path string `json:"path"`
	Kind string `json:"kind"`
}

func sortManagedBoundaries(boundaries []appArmorManagedBoundary) []appArmorManagedBoundary {
	sorted := make([]appArmorManagedBoundary, len(boundaries))
	copy(sorted, boundaries)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Path != sorted[j].Path {
			return sorted[i].Path < sorted[j].Path
		}
		return sorted[i].Kind < sorted[j].Kind
	})
	deduped := make([]appArmorManagedBoundary, 0, len(sorted))
	for i, boundary := range sorted {
		if i > 0 && boundary.Path == deduped[len(deduped)-1].Path {
			continue
		}
		deduped = append(deduped, boundary)
	}
	return deduped
}

func renderFragment(boundaries []appArmorManagedBoundary) []byte {
	sorted := sortManagedBoundaries(boundaries)

	var buf bytes.Buffer

	buf.WriteString(fragmentHeader1 + "\n")
	buf.WriteString(fragmentHeader2 + "\n")

	for _, boundary := range sorted {
		escaped := escapeAppArmorPath(boundary.Path)
		buf.WriteString("\n")
		if boundary.Kind == appArmorBoundaryRegularFile {
			// A regular-file boundary grants read reachability to exactly
			// that file: the trailing-slash and descendant rules would
			// never match a file. The kind is persisted in the fragment so
			// every re-render reproduces the exact-file rule without
			// consulting mutable host state.
			meta, _ := json.Marshal(appArmorBoundaryFileMeta{Path: boundary.Path, Kind: appArmorBoundaryFileMarker})
			buf.WriteString("# root-json: " + string(meta) + "\n")
			buf.WriteString("\"" + escaped + "\" r,\n")
			continue
		}
		buf.WriteString("# root-json: " + jsonQuote(boundary.Path) + "\n")
		buf.WriteString("\"" + escaped + "/\" r,\n")
		buf.WriteString("\"" + escaped + "/**\" r,\n")
	}

	return buf.Bytes()
}

func parseFragment(data []byte) ([]appArmorManagedBoundary, error) {
	content := string(data)
	if !strings.HasSuffix(content, "\n") {
		return nil, errors.New("fragment missing trailing newline")
	}

	lines := strings.Split(content, "\n")

	if len(lines) < 2 {
		return nil, errors.New("fragment too short")
	}
	if lines[0] != fragmentHeader1 {
		return nil, errors.New("fragment header mismatch")
	}
	if lines[1] != fragmentHeader2 && lines[1] != legacyFragmentHeader2 {
		return nil, errors.New("fragment header mismatch")
	}

	var boundaries []appArmorManagedBoundary
	for i := 2; i < len(lines); i++ {
		line := lines[i]
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "# root-json: ") {
			metadata := strings.TrimPrefix(line, "# root-json: ")
			boundary, err := parseRootJSONBoundary(metadata)
			if err != nil {
				return nil, fmt.Errorf("malformed root-json metadata at line %d: %w", i+1, err)
			}
			if err := validateBoundaryLexical(boundary.Path); err != nil {
				return nil, fmt.Errorf("invalid root at line %d: %w", i+1, err)
			}
			boundaries = append(boundaries, boundary)
		}
	}

	deduped := sortManagedBoundaries(boundaries)

	expected := renderFragment(deduped)
	legacyExpected := bytes.Replace(expected, []byte(fragmentHeader2+"\n"), []byte(legacyFragmentHeader2+"\n"), 1)
	if !bytes.Equal(data, expected) && !bytes.Equal(data, legacyExpected) {
		return nil, errors.New("fragment content does not match expected format (manually modified?)")
	}

	return deduped, nil
}

// parseRootJSONBoundary parses one root-json metadata value. The quoted-path
// form is the legacy representation and is always a directory boundary (the
// pre file-root fragments represented directory boundaries only); the
// object form carries the stable kind for a regular-file boundary. Any
// other JSON shape fails closed.
func parseRootJSONBoundary(metadata string) (appArmorManagedBoundary, error) {
	var legacy string
	if err := json.Unmarshal([]byte(metadata), &legacy); err == nil {
		return appArmorManagedBoundary{Path: legacy, Kind: appArmorBoundaryDirectory}, nil
	}
	var meta appArmorBoundaryFileMeta
	if err := json.Unmarshal([]byte(metadata), &meta); err != nil {
		return appArmorManagedBoundary{}, fmt.Errorf("not a boundary metadata value: %w", err)
	}
	if meta.Kind != appArmorBoundaryFileMarker {
		return appArmorManagedBoundary{}, fmt.Errorf("unknown boundary kind %q", meta.Kind)
	}
	return appArmorManagedBoundary{Path: meta.Path, Kind: appArmorBoundaryRegularFile}, nil
}

func (m *appArmorProfileManager) acquireAppArmorLock() (*os.File, error) {
	if err := os.MkdirAll(filepath.Dir(m.lockPath), 0755); err != nil {
		return nil, fmt.Errorf("cannot create lock directory: %w", err)
	}

	f, err := os.OpenFile(m.lockPath, os.O_CREATE|os.O_RDWR, 0600)
	if err != nil {
		return nil, fmt.Errorf("cannot open lock file: %w", err)
	}

	if err := syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		f.Close()
		if err == syscall.EWOULDBLOCK {
			return nil, errors.New("another apparmor operation is in progress")
		}
		return nil, fmt.Errorf("cannot acquire lock: %w", err)
	}

	return f, nil
}

func (m *appArmorProfileManager) readFragment() ([]appArmorManagedBoundary, error) {
	info, err := os.Lstat(m.managedFragmentPath)
	if err != nil {
		if os.IsNotExist(err) {
			return []appArmorManagedBoundary{}, nil
		}
		return nil, fmt.Errorf("cannot stat managed fragment: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil, errors.New("managed fragment path is a symlink")
	}
	if !info.Mode().IsRegular() {
		return nil, errors.New("managed fragment is not a regular file")
	}

	data, err := os.ReadFile(m.managedFragmentPath)
	if err != nil {
		return nil, fmt.Errorf("cannot read managed fragment: %w", err)
	}

	return parseFragment(data)
}

func (m *appArmorProfileManager) writeFragment(boundaries []appArmorManagedBoundary) error {
	dir := filepath.Dir(m.managedFragmentPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("cannot create fragment directory: %w", err)
	}

	data := renderFragment(boundaries)

	tmp, err := os.CreateTemp(dir, "managed-boundaries-*.tmp")
	if err != nil {
		return fmt.Errorf("cannot create temp file: %w", err)
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot write temp file: %w", err)
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot set temp file mode: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot close temp file: %w", err)
	}
	if err := os.Rename(tmpName, m.managedFragmentPath); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot rename temp file: %w", err)
	}

	return nil
}

func (m *appArmorProfileManager) reloadProfile() error {
	return m.runParser(m.parserPath, []string{"--replace", "--skip-cache", m.mainProfilePath})
}

func (m *appArmorProfileManager) validateProfile() error {
	return m.runParser(m.parserPath, []string{"--skip-kernel-load", "--skip-cache", m.mainProfilePath})
}

type fragmentSnapshot struct {
	exists     bool
	data       []byte
	mode       os.FileMode
	boundaries []appArmorManagedBoundary
}

func (m *appArmorProfileManager) snapshotFragment() (*fragmentSnapshot, error) {
	info, err := os.Lstat(m.managedFragmentPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &fragmentSnapshot{exists: false}, nil
		}
		return nil, fmt.Errorf("cannot lstat managed fragment: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil, errors.New("managed fragment path is a symlink")
	}
	if !info.Mode().IsRegular() {
		return nil, errors.New("managed fragment is not a regular file")
	}

	data, err := os.ReadFile(m.managedFragmentPath)
	if err != nil {
		return nil, fmt.Errorf("cannot read managed fragment: %w", err)
	}

	boundaries, err := parseFragment(data)
	if err != nil {
		return nil, fmt.Errorf("fragment parse error: %w", err)
	}

	return &fragmentSnapshot{
		exists:     true,
		data:       data,
		mode:       info.Mode().Perm(),
		boundaries: boundaries,
	}, nil
}

func (m *appArmorProfileManager) checkPrerequisites() error {
	info, err := os.Stat(m.parserPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("apparmor_parser not found: %s", m.parserPath)
		}
		return fmt.Errorf("cannot stat apparmor_parser: %w", err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("apparmor_parser is not a regular file: %s", m.parserPath)
	}
	if info.Mode().Perm()&0111 == 0 {
		return fmt.Errorf("apparmor_parser is not executable: %s", m.parserPath)
	}

	pinfo, err := os.Stat(m.mainProfilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("main profile not found: %s", m.mainProfilePath)
		}
		return fmt.Errorf("cannot stat main profile: %w", err)
	}
	if !pinfo.Mode().IsRegular() {
		return fmt.Errorf("main profile is not a regular file: %s", m.mainProfilePath)
	}

	return nil
}

func (m *appArmorProfileManager) restoreFragmentFile(snap *fragmentSnapshot) error {
	if !snap.exists {
		err := os.Remove(m.managedFragmentPath)
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return fmt.Errorf("cannot remove fragment during rollback: %w", err)
		}
		return nil
	}

	dir := filepath.Dir(m.managedFragmentPath)
	tmp, err := os.CreateTemp(dir, "managed-boundaries-*.tmp")
	if err != nil {
		return fmt.Errorf("cannot create rollback temp file: %w", err)
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(snap.data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot write rollback temp file: %w", err)
	}
	if err := tmp.Chmod(snap.mode); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("cannot set rollback temp file mode: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot close rollback temp file: %w", err)
	}
	if err := os.Rename(tmpName, m.managedFragmentPath); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("cannot rename rollback temp file: %w", err)
	}

	return nil
}

func (m *appArmorProfileManager) rollbackFragment(snap *fragmentSnapshot) error {
	if err := m.restoreFragmentFile(snap); err != nil {
		return err
	}
	if err := m.reloadProfile(); err != nil {
		return err
	}
	return nil
}

func (m *appArmorProfileManager) listManagedBoundaries() ([]appArmorManagedBoundary, error) {
	return m.readFragment()
}

func (m *appArmorProfileManager) addManagedBoundary(path string) (boundaryResult, error) {
	canonical, kind, err := validateBoundaryPathForAdd(path)
	if err != nil {
		return boundaryResult{}, err
	}

	lockFile, err := m.acquireAppArmorLock()
	if err != nil {
		return boundaryResult{}, err
	}
	defer lockFile.Close()

	if err := m.checkPrerequisites(); err != nil {
		return boundaryResult{}, err
	}

	snap, err := m.snapshotFragment()
	if err != nil {
		return boundaryResult{}, err
	}

	for _, r := range snap.boundaries {
		if r.Path == canonical {
			// The boundary is already managed with its persisted kind; the
			// add is idempotent and never re-derives the kind from host
			// state.
			return boundaryResult{Path: canonical, Changed: false}, nil
		}
	}

	newBoundaries := append(append([]appArmorManagedBoundary{}, snap.boundaries...),
		appArmorManagedBoundary{Path: canonical, Kind: kind})

	if err := m.writeFragment(newBoundaries); err != nil {
		return boundaryResult{}, err
	}

	if err := m.reloadProfile(); err != nil {
		rollbackErr := m.rollbackFragment(snap)
		if rollbackErr != nil {
			return boundaryResult{}, fmt.Errorf("reload failed: %v; rollback also failed: %v", err, rollbackErr)
		}
		return boundaryResult{}, fmt.Errorf("reload failed: %w", err)
	}

	return boundaryResult{Path: canonical, Changed: true}, nil
}

func (m *appArmorProfileManager) removeManagedBoundary(path string) (boundaryResult, error) {
	canonical, err := validateBoundaryPathForRemove(path)
	if err != nil {
		return boundaryResult{}, err
	}

	lockFile, err := m.acquireAppArmorLock()
	if err != nil {
		return boundaryResult{}, err
	}
	defer lockFile.Close()

	if err := m.checkPrerequisites(); err != nil {
		return boundaryResult{}, err
	}

	snap, err := m.snapshotFragment()
	if err != nil {
		return boundaryResult{}, err
	}

	newBoundaries := make([]appArmorManagedBoundary, 0, len(snap.boundaries))
	found := false
	for _, r := range snap.boundaries {
		if r.Path == canonical {
			found = true
		} else {
			newBoundaries = append(newBoundaries, r)
		}
	}

	if !found {
		return boundaryResult{Path: canonical, Changed: false}, nil
	}

	if err := m.writeFragment(newBoundaries); err != nil {
		return boundaryResult{}, err
	}

	if err := m.reloadProfile(); err != nil {
		rollbackErr := m.rollbackFragment(snap)
		if rollbackErr != nil {
			return boundaryResult{}, fmt.Errorf("reload failed: %v; rollback also failed: %v", err, rollbackErr)
		}
		return boundaryResult{}, fmt.Errorf("reload failed: %w", err)
	}

	return boundaryResult{Path: canonical, Changed: true}, nil
}

func (m *appArmorProfileManager) check() error {
	if err := m.checkPrerequisites(); err != nil {
		return err
	}

	boundaries, err := m.readFragment()
	if err != nil {
		return fmt.Errorf("managed fragment is malformed: %w", err)
	}

	// Diagnose managed boundaries that violate the workspace-path policy.
	for _, boundary := range boundaries {
		if err := validateWorkspacePathPolicy(boundary.Path); err != nil {
			return fmt.Errorf("managed boundary %q violates workspace root policy: %s", boundary.Path, err)
		}
	}

	if err := m.validateProfile(); err != nil {
		return fmt.Errorf("profile validation failed: %w", err)
	}

	return nil
}
