package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"
)

// TestOperationLogsResponseBoundedForAdversarialBytes proves that one HTTP
// logs response never materializes the full retained log: an operation whose
// workload emits more than one response chunk of JSON-hostile control bytes
// answers with a bounded chunk. RED evidence at the starting SHA: a single
// ~80-byte request materializes the whole retained buffer and expands it up to
// the measured 6× JSON-encoding amplification.
func TestOperationLogsResponseBoundedForAdversarialBytes(t *testing.T) {
	app := newTestAppWithAdminTokenAndStaging(t)
	app.OperationSupervisor = newOperationSupervisor()
	result, err := createDefaultAdminSessionForTest(app, testWorkspaceDir(t, app.Config.AllowedRoots[0].Path))
	if err != nil {
		t.Fatalf("createSession: %v", err)
	}
	if err := os.WriteFile(filepath.Join(result.Session.Workspace, "Dockerfile"), []byte("FROM alpine\n"), 0644); err != nil {
		t.Fatal(err)
	}

	// The fake workload emits more than one raw response chunk of the
	// measured worst-case JSON-expansion byte (control character 0x01)
	// and then stays alive so the operation remains running.
	readyFile := filepath.Join(t.TempDir(), "ready")
	releaseFile := filepath.Join(t.TempDir(), "release")
	app.ExecCommandContext = func(ctx context.Context, name string, args ...string) *exec.Cmd {
		// Emit 3 raw response chunks of the worst-case JSON-expansion byte
		// (control character 0x01), then stay alive so the operation remains
		// running. The bytes are generated by the shell, never placed in argv
		// (MAX_ARG_STRLEN bounds argv entries at 32 KiB).
		return exec.CommandContext(ctx, "/bin/sh", "-c",
			"head -c "+fmt.Sprint(3*logResponseChunkBytes)+" /dev/zero | tr '\\0' '\\001'; touch "+readyFile+
				"; while [ ! -f "+releaseFile+" ]; do sleep 0.1; done")
	}

	t.Cleanup(func() {
		_ = os.WriteFile(releaseFile, nil, 0644)
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		app.OperationSupervisor.terminateForShutdown(ctx, nil)
	})

	req := newBuildRequest(map[string]any{
		"context":    ".",
		"dockerfile": "Dockerfile",
		"image":      "example:test",
	}, result.Token)
	w := httptest.NewRecorder()
	app.handleBuild(w, req)
	if w.Code != http.StatusCreated {
		t.Fatalf("build: expected %d, got %d (%s)", http.StatusCreated, w.Code, w.Body.String())
	}
	var created operationCreatedResponse
	if err := json.Unmarshal(w.Body.Bytes(), &created); err != nil {
		t.Fatalf("decode create response: %v", err)
	}
	waitProcessReady(t, readyFile)

	logsReq := httptest.NewRequest(http.MethodGet, "/operations/"+created.OperationID+"/logs", nil)
	logsReq.Header.Set("Authorization", "Bearer "+result.Token)
	logsW := httptest.NewRecorder()
	newOperationMux(app).ServeHTTP(logsW, logsReq)

	if logsW.Code != http.StatusOK {
		t.Fatalf("logs: expected %d, got %d", http.StatusOK, logsW.Code)
	}

	// Documented encoded-response bound: the worst-case 6× expansion of one
	// raw chunk plus the response envelope.
	const encodedResponseBound = 6*logResponseChunkBytes + 4096
	if got := logsW.Body.Len(); got > encodedResponseBound {
		t.Fatalf("one logs response materialized %d encoded bytes (bound %d): the full retained log was expanded", got, encodedResponseBound)
	}
	if logsW.Body.Len() == 0 {
		t.Fatal("expected log output in the bounded response")
	}
}
