#!/usr/bin/env bash
#
# Release 2.2 M0-A feasibility proof.
#
# This is deliberately test-only infrastructure. It does not call the
# docker-helper API and it does not modify the shipped daemon profile. The
# generated workload profile starts from the Moby docker-default policy shape
# and adds only target-path write denials for the resolved read-only exposure.

set -Eeuo pipefail

PREFIX='[release-2.2-m0-apparmor]'
IMAGE="${M0_APPARMOR_IMAGE:-alpine:3.20}"
EVIDENCE_DIR="${M0_EVIDENCE_DIR:-/tmp/docker-helper-release-2.2-m0-apparmor-evidence}"
RUN_KEY_RAW="${GITHUB_RUN_ID:-local}-${GITHUB_RUN_ATTEMPT:-0}-$$"
RUN_KEY="$(printf '%s' "$RUN_KEY_RAW" | tr -c 'A-Za-z0-9_' '_')"
PROFILE_NAME="docker-helper-m0-aa-${RUN_KEY}"
ESCAPE_PROFILE_NAME="docker-helper-m0-aa-escape-${RUN_KEY}"
FOREIGN_PROFILE_NAME="foreign-m0-aa-${RUN_KEY}"
CONTAINER_NAME="docker-helper-m0-aa-${RUN_KEY}"
COLLISION_NAME="docker-helper-m0-aa-failure-${RUN_KEY}"
WORK_DIR="$(mktemp -d /tmp/docker-helper-m0-apparmor.XXXXXXXX)"
STATE_DIR="$WORK_DIR/owned-profiles"
PROFILE_FILE="$STATE_DIR/$PROFILE_NAME.profile"
ESCAPE_PROFILE_FILE="$WORK_DIR/$ESCAPE_PROFILE_NAME.profile"
FOREIGN_PROFILE_FILE="$WORK_DIR/$FOREIGN_PROFILE_NAME.profile"
RW_SOURCE="$WORK_DIR/rw-source"
RO_SOURCE="$WORK_DIR/ro-source"
RW_TARGET='/m0/rw'
RO_TARGET='/m0/ro'
ESCAPE_SENTINEL="$WORK_DIR/literal*star"
ESCAPE_NEIGHBOR="$WORK_DIR/literal-expanded-star"

say() {
  printf '%s %s\n' "$PREFIX" "$*"
}

fail() {
  printf '%s FAILED: %s\n' "$PREFIX" "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

profile_loaded() {
  local name="$1"
  grep -Fq "$name (" /sys/kernel/security/apparmor/profiles 2>/dev/null
}

remove_profile() {
  local name="$1" source_file="$2"
  if profile_loaded "$name"; then
    apparmor_parser --remove "$source_file"
  fi
}

cleanup() {
  local original_status=$?
  trap - EXIT INT TERM
  set +e
  docker rm -f "$CONTAINER_NAME" "$COLLISION_NAME" >/dev/null 2>&1
  remove_profile "$PROFILE_NAME" "$PROFILE_FILE" >/dev/null 2>&1
  remove_profile "$ESCAPE_PROFILE_NAME" "$ESCAPE_PROFILE_FILE" >/dev/null 2>&1
  remove_profile "$FOREIGN_PROFILE_NAME" "$FOREIGN_PROFILE_FILE" >/dev/null 2>&1
  case "$WORK_DIR" in
    /tmp/docker-helper-m0-apparmor.*) rm -rf -- "$WORK_DIR" ;;
  esac
  exit "$original_status"
}
trap cleanup EXIT INT TERM

# aa_path_literal converts a Linux path into an AppArmor quoted AARE literal.
# Slash and a conservative ASCII set remain readable; every other UTF-8 byte
# is emitted as an AppArmor hex escape. In particular, no caller byte can
# become a quote, comment marker, brace expansion, glob, or profile delimiter.
aa_path_literal() {
  python3 - "$1" <<'PY'
import os
import sys

raw = os.fsencode(sys.argv[1])
safe = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/._-"
sys.stdout.write("".join(chr(byte) if byte in safe else f"\\x{byte:02x}" for byte in raw))
PY
}

write_profile() {
  local ro_literal abi_line
  ro_literal="$(aa_path_literal "$RO_TARGET")"
  abi_line=''
  if [ -r /etc/apparmor.d/abi/3.0 ]; then
    abi_line='abi <abi/3.0>,'
  fi

  # Baseline rules follow the Moby docker-default AppArmor template. The two
  # final audit-deny rules are the M0 candidate projection.
  # Source baseline:
  # https://github.com/moby/profiles/blob/61eaf32614c7c71b60bd8927d3e6a4ffc8ff1f31/apparmor/template.go
  cat >"$PROFILE_FILE" <<EOF
# Generated by docker-helper Release 2.2 M0-A proof. Do not install.
# docker-helper-m0-owned: $RUN_KEY
$abi_line
#include <tunables/global>

profile "$PROFILE_NAME" flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>

  network,
  deny network alg,
  deny network vsock,
  capability,
  file,
  umount,
  signal (receive) peer=unconfined,
  signal (receive) peer=runc,
  signal (receive) peer=crun,
  signal (send,receive) peer="$PROFILE_NAME",

  deny @{PROC}/* w,
  deny @{PROC}/{[^1-9/],[^1-9/][^0-9/],[^1-9s/][^0-9y/][^0-9s/],[^1-9/][^0-9/][^0-9/][^0-9/]*}/** w,
  deny @{PROC}/sys/[^k]** w,
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/kcore rwklx,
  deny mount,
  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/firmware/** rwklx,
  deny /sys/devices/virtual/powercap/** rwklx,
  deny /sys/kernel/security/** rwklx,
  ptrace (trace,tracedby,read,readby) peer="$PROFILE_NAME",

  audit deny "$ro_literal/{,**}" wkl,
}
EOF
}

write_escape_profile() {
  local sentinel_literal
  sentinel_literal="$(aa_path_literal "$ESCAPE_SENTINEL")"
  cat >"$ESCAPE_PROFILE_FILE" <<EOF
# Test-only literal-encoding profile. Do not install.
#include <tunables/global>
profile "$ESCAPE_PROFILE_NAME" flags=(attach_disconnected,mediate_deleted) {
  file,
  audit deny "$sentinel_literal" wkl,
}
EOF
}

write_foreign_profile() {
  cat >"$FOREIGN_PROFILE_FILE" <<EOF
# Deliberately not helper-owned reconciliation state.
#include <tunables/global>
profile "$FOREIGN_PROFILE_NAME" flags=(attach_disconnected,mediate_deleted) {
  file,
}
EOF
}

assert_escape_contract() {
  local sample escaped token
  sample=$'/m0/space * ? [ ] { } # " \\'
  escaped="$(aa_path_literal "$sample")"
  for token in '\x20' '\x2a' '\x3f' '\x5b' '\x5d' '\x7b' '\x7d' '\x23' '\x22' '\x5c'; do
    case "$escaped" in
      *"$token"*) ;;
      *) fail "AppArmor literal encoder did not escape $token in: $escaped" ;;
    esac
  done
}

load_profile() {
  apparmor_parser --replace --skip-read-cache "$PROFILE_FILE"
  profile_loaded "$PROFILE_NAME" || fail "generated workload profile was not loaded"
}

unload_profile() {
  remove_profile "$PROFILE_NAME" "$PROFILE_FILE"
  if profile_loaded "$PROFILE_NAME"; then
    fail "generated workload profile remained loaded after removal"
  fi
}

reconcile_owned_profiles() {
  local source_file
  shopt -s nullglob
  for source_file in "$STATE_DIR"/docker-helper-m0-aa-*.profile; do
    grep -Fq '# docker-helper-m0-owned:' "$source_file" \
      || fail "owned profile lacks ownership marker: $source_file"
    apparmor_parser --remove "$source_file"
  done
  shopt -u nullglob
}

mkdir -p "$EVIDENCE_DIR" "$STATE_DIR" "$RW_SOURCE" "$RO_SOURCE"
chmod 0700 "$STATE_DIR"
chmod 0777 "$RW_SOURCE" "$RO_SOURCE"
printf 'rw-seed\n' >"$RW_SOURCE/seed.txt"
printf 'ro-seed\n' >"$RO_SOURCE/seed.txt"
chmod 0666 "$RW_SOURCE/seed.txt" "$RO_SOURCE/seed.txt"
printf 'protected\n' >"$ESCAPE_SENTINEL"
printf 'neighbor\n' >"$ESCAPE_NEIGHBOR"
chmod 0666 "$ESCAPE_SENTINEL" "$ESCAPE_NEIGHBOR"

for command_name in docker apparmor_parser aa-exec aa-status python3 sha256sum; do
  require_command "$command_name"
done
[ "$(id -u)" -eq 0 ] || fail 'proof must run as root'
[ "$(tr -d '[:space:]' </sys/module/apparmor/parameters/enabled 2>/dev/null)" = 'Y' ] \
  || fail 'AppArmor is not enabled'
[ -r /sys/kernel/security/apparmor/profiles ] || fail 'AppArmor profile inventory is not readable'
docker info >/dev/null 2>&1 || fail 'Docker daemon is not reachable'
docker info --format '{{json .SecurityOptions}}' | grep -q 'apparmor' \
  || fail 'Docker does not report AppArmor as an active security option'

exec > >(tee "$EVIDENCE_DIR/proof.log") 2>&1

say "run key: $RUN_KEY"
say "kernel: $(uname -srvm)"
say "image: $IMAGE"
docker version >"$EVIDENCE_DIR/docker-version.txt"
docker info >"$EVIDENCE_DIR/docker-info.txt"
aa-status >"$EVIDENCE_DIR/aa-status-before.txt"

assert_escape_contract
write_profile
write_escape_profile
write_foreign_profile
cp "$PROFILE_FILE" "$EVIDENCE_DIR/generated-workload.profile"
cp "$ESCAPE_PROFILE_FILE" "$EVIDENCE_DIR/path-literal-test.profile"
apparmor_parser --preprocess "$PROFILE_FILE" >"$EVIDENCE_DIR/generated-workload.preprocessed"

# Establish a fresh audit window before any intentional generated-profile deny.
AA_AUDIT_START_EPOCH="$(date +%s)"
export AA_AUDIT_START_EPOCH
# shellcheck source=/dev/null
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/uat-mac-apparmor.sh"

say 'prove literal-path escaping does not widen to a glob neighbor'
apparmor_parser --replace --skip-read-cache "$ESCAPE_PROFILE_FILE"
profile_loaded "$ESCAPE_PROFILE_NAME" || fail 'literal-encoding test profile was not loaded'
if aa-exec -p "$ESCAPE_PROFILE_NAME" -- sh -c "printf denied >>\"\$1\"" sh "$ESCAPE_SENTINEL"; then
  fail 'literal sentinel write unexpectedly succeeded'
fi
aa-exec -p "$ESCAPE_PROFILE_NAME" -- sh -c "printf allowed >>\"\$1\"" sh "$ESCAPE_NEIGHBOR" \
  || fail 'escaped literal denial widened to a neighboring pathname'
remove_profile "$ESCAPE_PROFILE_NAME" "$ESCAPE_PROFILE_FILE"

say 'prove both bind mounts are writable without the generated MAC profile'
docker pull "$IMAGE" >/dev/null
docker run --rm --security-opt apparmor=unconfined \
  --mount "type=bind,source=$RW_SOURCE,target=$RW_TARGET" \
  --mount "type=bind,source=$RO_SOURCE,target=$RO_TARGET" \
  "$IMAGE" sh -euc '
    printf control > /m0/rw/control.txt
    printf control > /m0/ro/control.txt
    rm /m0/rw/control.txt /m0/ro/control.txt
  '
if [ -e "$RW_SOURCE/control.txt" ] || [ -e "$RO_SOURCE/control.txt" ]; then
  fail 'control-container cleanup did not restore the source trees'
fi

RO_HASH_BEFORE="$(sha256sum "$RO_SOURCE/seed.txt" | awk '{print $1}')"

say 'prove mixed RW/RO behavior under the generated workload profile'
load_profile
docker run --name "$CONTAINER_NAME" --security-opt "apparmor=$PROFILE_NAME" \
  --mount "type=bind,source=$RW_SOURCE,target=$RW_TARGET" \
  --mount "type=bind,source=$RO_SOURCE,target=$RO_TARGET" \
  "$IMAGE" sh -euc '
    grep -F "docker-helper-m0-aa-" /proc/self/attr/current
    grep -Fx ro-seed /m0/ro/seed.txt
    printf allowed > /m0/rw/created.txt
    if sh -c "printf denied >> /m0/ro/seed.txt"; then exit 41; fi
    if touch /m0/ro/created.txt; then exit 42; fi
    if rm /m0/ro/seed.txt; then exit 43; fi
    if mv /m0/ro/seed.txt /m0/ro/renamed.txt; then exit 44; fi
    test -f /m0/ro/seed.txt
    test ! -e /m0/ro/created.txt
    test ! -e /m0/ro/renamed.txt
  '
docker rm "$CONTAINER_NAME" >/dev/null

[ -f "$RW_SOURCE/created.txt" ] || fail 'RW target did not persist its write'
RO_HASH_AFTER="$(sha256sum "$RO_SOURCE/seed.txt" | awk '{print $1}')"
[ "$RO_HASH_AFTER" = "$RO_HASH_BEFORE" ] || fail 'RO source content changed'
if [ -e "$RO_SOURCE/created.txt" ] || [ -e "$RO_SOURCE/renamed.txt" ]; then
  fail 'RO source gained mutation residue'
fi

PROFILE_AUDIT="$EVIDENCE_DIR/generated-profile-audit.log"
audit_records 'apparmor="DENIED"' \
  | grep -F "profile=\"$PROFILE_NAME\"" >"$PROFILE_AUDIT" || true
[ -s "$PROFILE_AUDIT" ] || fail 'no attributable AppArmor DENIED record for generated profile'
grep -F 'name="/m0/ro/' "$PROFILE_AUDIT" >/dev/null \
  || fail 'no workload-target AppArmor denial was captured'

unload_profile

say 'prove create-failure cleanup ordering'
load_profile
docker create --name "$COLLISION_NAME" "$IMAGE" true >/dev/null
if docker run --name "$COLLISION_NAME" --security-opt "apparmor=$PROFILE_NAME" "$IMAGE" true; then
  fail 'intentional Docker create failure unexpectedly succeeded'
fi
unload_profile
docker rm "$COLLISION_NAME" >/dev/null

say 'prove stale reconciliation is ownership bounded'
load_profile
apparmor_parser --replace --skip-read-cache "$FOREIGN_PROFILE_FILE"
profile_loaded "$FOREIGN_PROFILE_NAME" || fail 'foreign control profile did not load'
reconcile_owned_profiles
profile_loaded "$PROFILE_NAME" && fail 'owned stale profile survived reconciliation'
profile_loaded "$FOREIGN_PROFILE_NAME" || fail 'reconciliation removed foreign profile'
remove_profile "$FOREIGN_PROFILE_NAME" "$FOREIGN_PROFILE_FILE"

aa-status >"$EVIDENCE_DIR/aa-status-after.txt"
if profile_loaded "$PROFILE_NAME"; then
  fail 'generated profile residue remains at proof completion'
fi
if docker ps -a --format '{{.Names}}' | grep -Fxq "$CONTAINER_NAME"; then
  fail 'container residue remains at proof completion'
fi

cat >"$EVIDENCE_DIR/summary.txt" <<EOF
M0_A_RESULT=CLOSED
RUN_KEY=$RUN_KEY
PROFILE_NAME=$PROFILE_NAME
IMAGE=$IMAGE
KERNEL=$(uname -r)
APPARMOR_ENABLED=Y
VFS_WRITABLE_CONTROL=PASS
MIXED_RW_RO=PASS
MAC_ATTRIBUTABLE_DENIAL=PASS
PATH_LITERAL_ESCAPING=PASS
CREATE_FAILURE_CLEANUP=PASS
OWNERSHIP_BOUNDED_RECONCILIATION=PASS
PROFILE_RESIDUE=NONE
CONTAINER_RESIDUE=NONE
EOF

say 'M0-A CLOSED'
